/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'HelloWorld_cm0plus.Debug+FRDM-K32L3A6' 
 * Target:  'Debug+FRDM-K32L3A6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "fsl_device_registers.h"

/* NXP::Device:SDK Utilities:serial_manager_uart@1.0.0 */
#ifndef SERIAL_PORT_TYPE_UART
#define SERIAL_PORT_TYPE_UART 1
#endif


#endif /* RTE_COMPONENTS_H */
