name: Build Hello project
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'    

jobs:
  Build:
    strategy:

      matrix:
        target: [
          {proj: Hello,         folder: Hello,             board: AVH},
          {proj: HelloWorld,    folder: DualCore,          board: FRDM-K32L3A6},
          {proj: SimpleTZ,      folder: SimpleTrustZone,   board: FRDM-K32L3A6}
        ]

        # compiler: [AC6, GCC, Clang]
        compiler: [AC6]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build ${{ matrix.target.proj }} project
        working-directory: ./${{ matrix.target.folder }}/
        run: |
            cbuild ${{ matrix.target.proj }}.csolution.yml --update-rte --packs --toolchain ${{ matrix.compiler }} --rebuild

      - name: Upload ${{ matrix.target.proj }} build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.proj }}_${{ matrix.compiler }}
          path: |
            ./${{ matrix.target.folder }}/out/
          retention-days: 1
