name: "SimpleTZ: Test Build and Execution"
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - SimpleTrustZone/**
      - .github/workflows/SimpleTZ-CI.yml
  push:
    branches: [main]
    paths:
      - SimpleTrustZone/**
      - .github/workflows/SimpleTZ-CI.yml
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Build:
    strategy:
      matrix:

        compiler: [
          {name: AC6, ext: axf}
        ]
        build: [ 
          {type: Release},
          {type: Debug}
        ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build project CM33_s and CM33_ns for build-type ${{ matrix.build.type }} with ${{ matrix.compiler.name }}
        working-directory: ./SimpleTrustZone/
        run: cbuild SimpleTZ.csolution.yml --packs --context .${{ matrix.build.type }}+AVH --toolchain ${{ matrix.compiler.name }}


      - name: Execute project CM33_s and CM33_ns for build-type ${{ matrix.build.type }} with ${{ matrix.compiler.name }} using FVP_MPS2_Cortex-M33
        working-directory: ./SimpleTrustZone/
        run: |
            FVP_MPS2_Cortex-M33 \
            -a ./out/CM33_ns/AVH/${{ matrix.build.type }}/CM33_ns.${{ matrix.compiler.ext }} \
            -a ./out/CM33_s/AVH/${{ matrix.build.type }}/CM33_s.${{ matrix.compiler.ext }} \
            -f ./../FVP/FVP_MPS2_Cortex-M33/fvp_config.txt \
            --stat
