name:  Test Build and Execution
on:

  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Build:
    strategy:
      matrix:

        compiler: [
          {name: AC6, ext: axf},
          {name: GCC, ext: elf}
        ]
        build: [ 
          {type: Release},
          {type: Debug}
        ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build CM33_ns and CM33_ns contexts with ${{ matrix.compiler.name }} for ${{ matrix.build.type }}
        if: always()
        working-directory: ./SimpleTrustZone/
        run: |
            cbuild SimpleTZ.csolution.yml --update-rte --packs --context .${{ matrix.build.type }}+CS300 --toolchain ${{ matrix.compiler.name }}
    
      - name: Run CM33_s build with ${{ matrix.compiler.name }} and type ${{ matrix.build.type }}
        if: always()
        working-directory: ./SimpleTrustZone/
        run: |
            FVP_Corstone_SSE-300 -a ./out/CM33_s/CS300/${{ matrix.build.type }}/CM33_s.${{ matrix.compiler.ext }} -f ./../FVP/FVP_Corstone_SSE-300/fvp_config.txt \
            -C mps3_board.uart0.out_file=./out/CM33_s/CS300/${{ matrix.build.type }}/${{ matrix.compiler.name }}_CM33_s_fvp_stdout.log \
            --simlimit 60 --stat
            echo " Show simulation UART output for CM33_s build with ${{ matrix.compiler.name }} and type ${{ matrix.build.type }}"
            cat ./out/CM33_s/CS300/${{ matrix.build.type }}/${{ matrix.compiler.name }}_CM33_s_fvp_stdout.log

      - name: Run CM33_ns build with ${{ matrix.compiler.name }} and type ${{ matrix.build.type }}
        if: always()
        working-directory: ./SimpleTrustZone/
        run: |
            FVP_Corstone_SSE-300 -a ./out/CM33_ns/CS300/${{ matrix.build.type }}/CM33_ns.${{ matrix.compiler.ext }} -f ./../FVP/FVP_Corstone_SSE-300/fvp_config.txt \
            -C mps3_board.uart0.out_file=./out/CM33_ns/CS300/${{ matrix.build.type }}/${{ matrix.compiler.name }}_CM33_ns_fvp_stdout.log \
            --simlimit 60 --stat
             echo " Show simulation UART output for CM33_ns build with ${{ matrix.compiler.name }} and type ${{ matrix.build.type }}"
             cat ./out/CM33_ns/CS300/${{ matrix.build.type }}/${{ matrix.compiler.name }}_CM33_ns_fvp_stdout.log
