name: "SimpleTZ: Test Build and Execution"
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - SimpleTrustZone/**
      - .github/workflows/SimpleTZ-CI.yml
  push:
    branches: [main]
    paths:
      - SimpleTrustZone/**
      - .github/workflows/SimpleTZ-CI.yml
  schedule:
    - cron: '00 20 * * 6'

jobs:
  TrustZone:
    name: TrustZone (${{ matrix.build.type }}, ${{ matrix.compiler.name }})
    strategy:
      matrix:

        compiler: [
          {name: AC6, ext: axf},
          {name: GCC, ext: elf}
        ]
        build: [ 
          {type: Release},
          {type: Debug}
        ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1.3
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1.3

      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.14'

      - name: Build secure and non-secure projects
        working-directory: ./SimpleTrustZone/
        run: cbuild SimpleTZ.csolution.yml --packs --active AVH@${{ matrix.build.type }} --toolchain ${{ matrix.compiler.name }}

      - name: Execute secure and non-secure projects on FVP
        working-directory: ./SimpleTrustZone/
        run: |
            FVP_MPS2_Cortex-M33 \
            -a ./out/CM33_ns/AVH/${{ matrix.build.type }}/CM33_ns.${{ matrix.compiler.ext }} \
            -a ./out/CM33_s/AVH/${{ matrix.build.type }}/CM33_s.${{ matrix.compiler.ext }} \
            -f ./../FVP/FVP_MPS2_Cortex-M33/fvp_config.txt \
            --simlimit 10 --stat

  NonSecureOnly:
    name: Non-secure only (${{ matrix.build.type }}, ${{ matrix.compiler.name }})
    strategy:
      matrix:
        compiler: [
          {name: AC6, ext: axf},
          {name: GCC, ext: elf}
        ]
        build: [
          {type: Release},
          {type: Debug}
        ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1.3
        with:
          config: ".ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1.3

      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.14'

      - name: Build secure project to create HEX file and CMSE library
        working-directory: ./SimpleTrustZone/
        run: cbuild SimpleTZ.csolution.yml --packs --context CM33_s.${{ matrix.build.type }}+AVH --toolchain ${{ matrix.compiler.name }}

      - name: Build non-secure-only target
        working-directory: ./SimpleTrustZone/
        run: cbuild SimpleTZ.csolution.yml --context CM33_ns.${{ matrix.build.type }}+AVH-NS-only --toolchain ${{ matrix.compiler.name }}

      - name: Execute non-secure-only target on FVP
        working-directory: ./SimpleTrustZone/
        run: |
            FVP_MPS2_Cortex-M33 \
            -a ./out/CM33_s/AVH/${{ matrix.build.type }}/CM33_s.hex \
            -a ./out/CM33_ns/AVH-NS-only/${{ matrix.build.type }}/CM33_ns.${{ matrix.compiler.ext }} \
            -f ./../FVP/FVP_MPS2_Cortex-M33/fvp_config.txt \
            --simlimit 10 --stat
